
import React from 'react';
import { Module } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, PieChart, Pie } from 'recharts';
import { Trophy, TrendingUp, Target, Clock } from 'lucide-react';

interface ProgressReportProps {
  modules: Module[];
}

const ProgressReport: React.FC<ProgressReportProps> = ({ modules }) => {
  const allSubmodules = modules.flatMap(m => m.submodules);
  const completed = allSubmodules.filter(s => s.status === 'completed').length;
  const total = allSubmodules.length;
  const percentCompleted = total > 0 ? (completed / total) * 100 : 0;
  
  const scores = allSubmodules.filter(s => s.score !== undefined).map(s => s.score! * 100);
  const averageScore = scores.length > 0 ? scores.reduce((a, b) => a + b, 0) / scores.length : 0;

  const chartData = modules.map(m => {
    const moduleScores = m.submodules.filter(s => s.score !== undefined).map(s => s.score! * 100);
    return {
      name: m.title.length > 15 ? m.title.substring(0, 15) + '...' : m.title,
      score: moduleScores.length > 0 ? Math.round(moduleScores.reduce((a, b) => a + b, 0) / moduleScores.length) : 0,
    };
  });

  const pieData = [
    { name: 'Completed', value: completed, color: '#10b981' },
    { name: 'Remaining', value: total - completed, color: '#e2e8f0' }
  ];

  return (
    <div className="space-y-8 pb-20">
      <div className="mb-8">
        <h2 className="text-3xl font-black text-slate-900 tracking-tight">Progress Tracker</h2>
        <p className="text-slate-500 mt-2">Overall course analytics generated by the Progress Tracker Agent.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="bg-indigo-50 w-12 h-12 rounded-2xl flex items-center justify-center text-indigo-600 mb-4">
            <Target size={24} />
          </div>
          <div className="text-2xl font-black text-slate-900">{Math.round(percentCompleted)}%</div>
          <div className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-1">Course Progress</div>
        </div>

        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="bg-emerald-50 w-12 h-12 rounded-2xl flex items-center justify-center text-emerald-600 mb-4">
            <Trophy size={24} />
          </div>
          <div className="text-2xl font-black text-slate-900">{Math.round(averageScore)}%</div>
          <div className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-1">Average Quiz Score</div>
        </div>

        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="bg-amber-50 w-12 h-12 rounded-2xl flex items-center justify-center text-amber-600 mb-4">
            <Clock size={24} />
          </div>
          <div className="text-2xl font-black text-slate-900">{completed} / {total}</div>
          <div className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-1">Lessons Finished</div>
        </div>

        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="bg-rose-50 w-12 h-12 rounded-2xl flex items-center justify-center text-rose-600 mb-4">
            <TrendingUp size={24} />
          </div>
          <div className="text-2xl font-black text-slate-900">Steady</div>
          <div className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-1">Learning Momentum</div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 bg-white p-8 rounded-3xl border border-slate-200 shadow-sm">
          <h3 className="text-lg font-bold text-slate-800 mb-8 flex items-center gap-2">
             Performance by Module
          </h3>
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#94a3b8' }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#94a3b8' }} domain={[0, 100]} />
                <Tooltip 
                  cursor={{ fill: '#f8fafc' }}
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }}
                />
                <Bar dataKey="score" radius={[8, 8, 0, 0]} barSize={40}>
                  {chartData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.score > 70 ? '#10b981' : '#6366f1'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm flex flex-col items-center justify-center">
          <h3 className="text-lg font-bold text-slate-800 mb-4">Curriculum Health</h3>
          <div className="h-[200px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={pieData}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={80}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {pieData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="text-center mt-4">
             <div className="text-3xl font-black text-slate-900">{completed} Lessons</div>
             <p className="text-xs text-slate-400 font-bold uppercase mt-1">Mastery Achieved</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProgressReport;
